### ISSUE TITLE
Переподключение к ws ожидайте..

### ISSUE THREAD

**Issue by privatekey7** [sm1ck/snapshotvoter#1]
Всё установил, вроде норм, но после того как запустил - голосование, постоянная ошибка: Переподключение к ws ожидайте..

**Comment by sm1ck** [comment]
Странно, но тут бы логи увидеть какие-то и параметры запуска

**Comment by privatekey7** [comment]
https://imgur.com/a/dp8nxfH
https://imgur.com/a/jfHZXdZ
Cкрины из консоли

**Comment by sm1ck** [comment]
Судя по вашей консоли, у вас ошибка из-за того, что не заменили в express/vote/keys.json 
```
"приватный_ключ_1",
"приватный_ключ_2"
```
на ваши нормальные ключи к кошелькам

**Comment by privatekey7** [comment]
Я тоже об этом подумал, но суть в том что я их заменил

**Comment by sm1ck** [comment]
Значит не в той папке где-то, мне уже писали с такой проблемой и потом решили ее так

**Comment by sm1ck** [comment]
<img width="363" alt="Снимок экрана 2023-04-14 в 14 24 52" src="https://user-images.githubusercontent.com/45939749/232004550-6e91337b-0c88-4eb2-ae74-2a2c4eda07b7.png">
я бы посмотрел файл в этой папке еще раз

**Comment by privatekey7** [comment]
Всё в порядке с ключами https://imgur.com/a/vDfctDD

**Comment by privatekey7** [comment]
Получается всё таки проблема в указании кошелька, хотя указал я их правильно, как бы решить эту проблему?) Я в коде вообще не шарю) https://imgur.com/a/1r48oPt

**Comment by sm1ck** [comment]
Ваши ключи сохранены по адресу:
<img width="620" alt="Снимок экрана 2023-04-14 в 14 35 27" src="https://user-images.githubusercontent.com/45939749/232007569-313753f4-3301-47a1-8ec4-81c7bd708928.png">
Адрес же папки запуска:
![image](https://user-images.githubusercontent.com/45939749/232007654-197a2343-78e2-4cb1-bc01-9746c5e64d26.png)
Это разные папки.

**Comment by privatekey7** [comment]
Спасибо большое друг за поддержку и классный софт) в общем я ещё тот мамкин програмист)) я устанавливал скрипт через Git и он установился в C:\Users, а приватники поменял в папке со скриптом на рабочем столе) в итоге поменял там где надо и всё заработало)

**Comment by privatekey7** [comment]
А чем отличается голосование Approval от обычного?

**Comment by sm1ck** [comment]
Ну, там по сути разные типа голосования может указать проект при инициализации.
https://docs.snapshot.org/user-guides/proposals/voting-types#what-is-a-voting-system
По сути вроде как можно выбрать несколько вариантов когда. Но это зависит от конкретного проползала и его типа на странице.

**Comment by privatekey7** [comment]
Ещё раз от души дружище за помощь дружище)
