### ISSUE TITLE
IP check

### ISSUE THREAD

**Issue by vzablodskiy1999** [sm1ck/snapshotvoter#2]
Привет, не думаешь ли что обращение к ендпоинтам снепшота может привести к тому, что они могут сохранять айпи с которого пришел запрос?

**Comment by sm1ck** [comment]
Ну, они могут сохранить, а дальше в любой нормальной стране есть законы GDPR. Они не смогут прямо передать третьим лицам твои данные по типу кошелек - ip. Иначе их могут ждать гигантские штрафы. 
Тем более я использую официальную библиотеку, технически не запрещено это означает голосовать на множество кошельков с одного ip (что и очевидно).
